#!/usr/bin/env python3

import gi
import os

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

from ffripper.ui import main

builder = Gtk.Builder()
builder.add_from_file("{}/data/ffripper.glade".format(os.path.dirname(os.path.realpath(__file__))))

main(builder, "../data/")
