name: ffripper
version: '0.1'
summary: FFRipper
description: |
  A fast, powerful and simple to use Audio-CD ripper.
confinement: devmode
base: core18
license: GPL-3.0+
icon: data/ffripper.svg

parts:
  ffripper:
    plugin: python
    python-version: python3
    python-packages:
      - rich>=9.12.3
      - setuptools>=49.3.1
    source: https://github.com/ThePickwickClub/ffripper.git
    stage-packages:
      - python3-gi
      - python3-libdiscid
      - python3-musicbrainzngs
      - python3-yaml
      - ffmpeg
      - python3-pil

apps:
  ffripper:
    command: bin/ffripper
    extensions: [gnome-3-28]
    desktop: data/ffripper.desktop
